apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-prosessor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue-prosessor
  template:
    metadata:
      labels:
        app: queue-prosessor
    spec:
      containers:
        - name: worker
          image: keda-worker:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_HOST
              value: redis-master:6379
