apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: queue-prosessor-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: queue-prosessor # Must match your Deployment name
  minReplicaCount: 0 # Scale down to zero when no jobs exist!
  maxReplicaCount: 10 # Don't blow up your machine
  cooldownPeriod: 30 # How long to wait before scaling down after queue is empty
  triggers:
    - type: redis
      metadata:
        address: redis-master.default.svc.cluster.local:6379
        listName: job-queue
        listLength: "5" # Target value: 1 pod for every 5 items in the queue
